### PR TITLE
refactor: split up database initialization into two phases

### PR DESCRIPTION
**Pull request by BastiDood**
## Problem

Currently, the feedback loop for creating and editing SQL functions is frustrating because it requires us to edit the `db/init.sql` file. Doing so necessities a full reinitialization of the database. Many of you are too familiar with the struggle of...

```bash
rm -rf data
pnpm db:init && pnpm db:start
pnpm db:template && pnpm db:create hatid
```

## Solution

This PR splits the database initialization into two phases: **table creation** and **function creation**.

The table creation phase contains all `CREATE TABLE` steps in a new file named `db/tables.sql`. Any edits to `tables.sql` necessitate a full reinitialization of the database. However, at this stage in the project when all the tables have already been finalized, this should _rarely_ be the case.

Next, the function creation phase contains all `CREATE OR REPLACE FUNCTION` steps in a new file named `db/funcs.sql`. Any edits to the `funcs.sql` _do not_ require reinitialization. In fact, due to the `CREATE OR REPLACE` keyword, the script can actually be run as many times as possible. It can even be used as a mechanism to overwrite old versions of functions! Since we are editing SQL functions most of the time anyway, this approach should significantly improve the feedback loop.

## Workflow

No more `pnpm db:template`! Well, not really. We can still run `pnpm db:template` in the first initialization of a database, but we can now treat it as if it were an alias for two distinct subroutines: `pnpm db:table && pnpm db:func`.

The former (`pnpm db:table`) is only run _once_ per initialization while the latter (`pnpm db:func`) may be run as _many_ times as reasonably possible.

> **Warning**
> The `CREATE OR REPLACE` mechanism may leave dangling, unused functions lying around if not properly maintained.

```bash
# Runs `db/tables.sql` once!
pnpm db:table

# Runs `db/funcs.sql` many times!
pnpm db:func
pnpm db:func
pnpm db:func
pnpm db:func
pnpm db:func
```

### CODE REVIEW

**Review by FeelingITNoW — APPROVED** [review]
bmislgmt! Ty for this qol change

**Review by Anjellyrika — APPROVED** [review]
Thank you, very helpful 👍

**Review by Pecsooon — COMMENTED** [review]
SUBLIME!!!

**Review by Pecsooon — COMMENTED** [review]
superb!!

**Pull request merged**
