### PR TITLE
UI test

### PR DESCRIPTION
**Pull request by jgpecson2**
Fixed the layout for user dashboard and login page. The login page now contains an email and password input field aside from the sign in with google account. The dashboard now includes the frontend for the create label.

### CODE REVIEW

**Review by BastiDood — CHANGES_REQUESTED** [review]
* We need to remove the Git merge conflict indicators.
* We put a lot of common markup inside components so that we don't have to repeat the Tailwind classes everywhere.
  - Aside from that, the `.svelte` components have become too big that we need to componentize (if that's a word?) them anyway.

**Comment by BastiDood** [comment]
In hindsight, we might need to merge #16 first before this PR. #16 fixes a bunch of lints and formatting rules that we were not actually checking due to upstream bugs. I had to downgrade some dependencies to make it work.

Anyway, that entails one important thing when rebasing this branch. Since the `pnpm-lock.yaml` lockfiles will likely lead to conflicts, use the following procedure to resolve them.

```bash
# Get the latest commits after #16 is merged
git switch main
git pull
git rebase main

# 💥 At this point, there will probably be a
# merge conflict with the `pnpm-lock.yaml` file.

# Delete the conflicted file.
rm pnpm-lock.yaml

# Then let's just regenerate it.
pnpm add -D @tailwindcss/forms

# Then finally mark the conflict as resolved
# (assuming there are no other conflicts).
git add pnpm-lock.yaml
git rebase --continue
```

Note that there will likely be some more conflicts due to running `pnpm fmt` back in #16. Simply overwrite the boilerplate code with your own when that happens.

**Comment by BastiDood** [comment]
# Update

We're gonna need to fundamentally refactor the styling approach here. Currently, we manually edit the styles at the component-level with Tailwind classes. This is not in the spirit of the Skeleton design system. Note that Skeleton UI prescribes that CSS variables determine themes, themes determine design tokens (i.e., Tailwind classes), design tokens determine components, and finally components determine pages. Such a workflow enables Skeleton UI to trivially derive light and dark modes for the application. See this flow chart from the [documentation](https://www.skeleton.dev/docs/tokens):

Skeleton UI design theming workflow

We thus need to refactor the entire styling approach into a more theme-centric approach rather than manually tweaking the styles via Tailwind. Although this is possible, a Skeleton-centric UI will save us development time since many responsive design issues, light-dark interplays, and component stylings are already handled by the design system.

**Review by BastiDood — APPROVED** [review]
# Future Work

* Needs refactoring to use `AppRail`, `AppRailTile`, and `AppRailAnchor`.
* Restore the colors while using Skeleton's theming primitives.
* Use more "Svelte-y" patterns when dealing with inputs.
* Continue to remove component-level Tailwind classes. Instead, we should rely on Skeleton's default theming.
* Hook the client API wrappers to the actual buttons.
* Use the getters from #29 to render the real data instead of dummy data.
* Tweak the theme (if necessary).

**Review by Anjellyrika — APPROVED** [review]
What a journey! 🚀

**Review by FeelingITNoW — APPROVED** [review]
Pog bhslgtm!

**Pull request merged**
